package at.tugraz.ist.cc.symbol_table;

import java.util.Objects;


public class SymbolVariable {
    private final SymbolType type;
    private final Object actualType;
    private String name;
    private Object value;
    public Boolean isThisClass;

    // indicates if the variable is a variable from the code
    // or a variable which is introduced by us.
    private final boolean isAutogeneratedTempVar;

    public SymbolVariable(SymbolType type, Object actualType) {
        if (type == SymbolType.PRIMITIVE && !(actualType instanceof SymbolPrimitiveType) ||
                type == SymbolType.CLASS && !(actualType instanceof SymbolClass)) {
            System.exit(76);
        }
        this.isThisClass = false;
        this.type = type;
        this.actualType = actualType;
        this.name = "";
        this.value = null;
        this.isAutogeneratedTempVar = false;
    }

    public SymbolVariable(SymbolType type, Object actualType, String name) {
        if (type == SymbolType.PRIMITIVE && !(actualType instanceof SymbolPrimitiveType) ||
                type == SymbolType.CLASS && !(actualType instanceof SymbolClass)) {
            System.exit(76);
        }
        this.isThisClass = false;
        this.type = type;
        this.actualType = actualType;
        this.name = name;
        this.value = null;
        this.isAutogeneratedTempVar = false;
    }

    public SymbolVariable(SymbolType type, Object actualType, String name, Object value) {
        if (type == SymbolType.PRIMITIVE && !(actualType instanceof SymbolPrimitiveType) ||
                type == SymbolType.CLASS && !(actualType instanceof SymbolClass)) {
            System.exit(76);
        }
        this.isThisClass = false;
        this.type = type;
        this.actualType = actualType;
        this.name = name;
        this.value = value;
        this.isAutogeneratedTempVar = false;
    }

    public SymbolVariable(SymbolVariable source) {
        this.isThisClass = false;
        this.type = source.type;
        this.actualType = source.actualType;
        this.name = source.name;
        this.value = source.value;
        this.isAutogeneratedTempVar = false;
    }

    public SymbolVariable(SymbolVariable source, String name, boolean isAutogeneratedTempVar) {
        this.isThisClass = false;
        this.type = source.type;
        this.actualType = source.actualType;
        this.name = name;
        this.value = source.value;
        this.isAutogeneratedTempVar = isAutogeneratedTempVar;
    }

    public SymbolVariable(Object actualType, Boolean isThisClass) {
        this.actualType = actualType;
        this.isThisClass = isThisClass;
        this.value = null;
        this.type = SymbolType.CLASS;
        this.isAutogeneratedTempVar = false;
        this.name = null;
    }

    public SymbolType getType() {
        return type;
    }

    public Object getActualType() {
        return actualType;
    }

    public String getTypeAsString() {
        if (actualType instanceof SymbolClass) {
            return ((SymbolClass) actualType).getClassName();
        } else if (actualType instanceof SymbolPrimitiveType) {
            return ((SymbolPrimitiveType) actualType).toString().toLowerCase();
        } else {
            System.exit(77);
            return null;
        }
    }

    public String getName() {
        return name;
    }

    /**
     * This only checks if the name is equal
     *
     * @param o
     * @return
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SymbolVariable that = (SymbolVariable) o;
        return Objects.equals(name, that.name)
                && Objects.equals(isAutogeneratedTempVar, that.isAutogeneratedTempVar);
    }

    public boolean equalTypeAndActualType(SymbolVariable that) {
        return (type == SymbolType.PRIMITIVE && that.getType() == SymbolType.PRIMITIVE &&
                ((SymbolPrimitiveType) actualType).equals(that.getActualType()))
                ||
                (type == SymbolType.CLASS && that.getType() == SymbolType.CLASS &&
                        ((SymbolClass) actualType).getClassName().equals(((SymbolClass) that.getActualType()).getClassName()));
    }

    public Object getValue() {
        return value;
    }

    public void setValue(Object value) {
        this.value = value;
    }

    public void setName(String name) {
        this.name = name;
    }
}
